Repository dotnet/spark, pull requests merged in 2019-05, with the labels that each got.

#80 Worker installation script changes to deal with versioning
  deployment/install-worker.sh
Labels: bug

#81 Remove formatPath() that adds ".\" or "./" to the executable.
  README.md
  src/scala/microsoft-spark-2.3.x/src/main/scala/org/apache/spark/deploy/DotnetRunner.scala
  src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/deploy/DotnetRunner.scala
Labels: enhancement

#82 Automate packaging release artifacts
  azure-pipelines.yml
  script/package-worker.ps1
Labels: infrastructure

#89 [Doc] Separate out and link Get Started Instructions
  README.md
  deployment/README.md
  deployment/db-init.sh
  docs/getting-started/getting-started-ubuntu-spark-net.md
  docs/getting-started/ubuntu-instructions.md
  docs/getting-started/windows-instructions.md
Labels: documentation

#92 Simplify configuration service.
  azure-pipelines.yml
  src/csharp/Microsoft.Spark.E2ETest/Microsoft.Spark.E2ETest.csproj
  src/csharp/Microsoft.Spark.E2ETest/SparkFixture.cs
  src/csharp/Microsoft.Spark/Interop/SparkEnvironment.cs
  src/csharp/Microsoft.Spark/Microsoft.Spark.csproj
  src/csharp/Microsoft.Spark/Network/DefaultSocketWrapper.cs
  src/csharp/Microsoft.Spark/Services/ConfigurationService.cs
  src/csharp/Microsoft.Spark/Services/IConfigurationService.cs
Labels: enhancement

#104 Create CODE_OF_CONDUCT.md.
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation
