Repository dotnet/spark, pull requests merged in 2019-04, with the labels that each got.

#16 Updating to reflect JIRA link and Nuget ETA
  README.md
Labels: documentation

#47 Updating README to reflect correct .NET Core version
  README.md
Labels: documentation

#51 Update Spark download link in Getting Started in README.md
  README.md
Labels: documentation

#54 Migrated nuspec to csproj and improved packaging
  .gitignore
  azure-pipelines.yml
  eng/Sign.proj
  examples/Directory.Build.props
  examples/Microsoft.Spark.CSharp.Examples/Microsoft.Spark.CSharp.Examples.csproj
  examples/Microsoft.Spark.FSharp.Examples/Microsoft.Spark.FSharp.Examples.fsproj
  src/csharp/Directory.Build.props
  src/csharp/Microsoft.Spark.Worker/Microsoft.Spark.Worker.csproj
  src/csharp/Microsoft.Spark.nuspec
  src/csharp/Microsoft.Spark/Microsoft.Spark.csproj
  src/csharp/Microsoft.Spark/build/netstandard2.0/Microsoft.Spark.targets
Labels: enhancement

#68 Remove version depedency from code in E2E test
  src/csharp/Microsoft.Spark.E2ETest/SparkFixture.cs
Labels: enhancement

#73 Updating Readme to reflect the use of dotnet.exe
  README.md
Labels: documentation

#71 Update build pipeline to use .NET Core 2.2.105
  azure-pipelines.yml
  examples/Directory.Build.props
  src/csharp/Directory.Build.props
  src/csharp/Microsoft.Spark.E2ETest/Microsoft.Spark.E2ETest.csproj
  src/csharp/Microsoft.Spark.UnitTest/Microsoft.Spark.UnitTest.csproj
  src/csharp/Microsoft.Spark.Worker.UnitTest/Microsoft.Spark.Worker.UnitTest.csproj
  src/csharp/Microsoft.Spark.Worker/Microsoft.Spark.Worker.csproj
  src/csharp/Microsoft.Spark/Microsoft.Spark.csproj
Labels: bug
