Repository dotnet/spark, pull requests merged in 2019-11, with the labels that each got.

#294 [Documentation] UDF debugging instruction
  docs/developer-guide.md
Labels: documentation

#306 Deploy Spark .Net REPL to HDI Spark Cluster with Notebook Experience
  deployment/HDI-Spark/Notebooks/README.md
  deployment/HDI-Spark/Notebooks/install-interactive-notebook.sh
  docs/img/HDI-Spark-Notebooks/add-sparkconfig.png
  docs/img/HDI-Spark-Notebooks/create-df.png
  docs/img/HDI-Spark-Notebooks/create-sparkdotnet-notebook.png
  docs/img/HDI-Spark-Notebooks/install-notebook-scriptaction.png
  docs/img/HDI-Spark-Notebooks/restart-affected.png
  docs/img/HDI-Spark-Notebooks/run-udf.png
  docs/img/HDI-Spark-Notebooks/select-ambari.png
  docs/img/HDI-Spark-Notebooks/select-host.png
  docs/img/HDI-Spark-Notebooks/select-livyserver.png
  docs/img/HDI-Spark-Notebooks/spark-configs.png
  docs/img/HDI-Spark-Notebooks/start-sparksession.png
  docs/img/HDI-Spark-Notebooks/stop-server.png
Labels: enhancement

#332 Remove SparkSession.*ActiveSession APIs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/SparkSessionTests.cs
  src/csharp/Microsoft.Spark/Sql/SparkSession.cs
Labels: bug

#248 Expose Schema() that takes in StructType
  examples/Microsoft.Spark.CSharp.Examples/Sql/Batch/Basic.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/DataFrameReaderTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/Streaming/DataStreamReaderTests.cs
  src/csharp/Microsoft.Spark/Sql/DataFrameReader.cs
  src/csharp/Microsoft.Spark/Sql/Expressions/UserDefinedFunction.cs
  src/csharp/Microsoft.Spark/Sql/Streaming/DataStreamReader.cs
  src/csharp/Microsoft.Spark/Sql/Types/DataType.cs
  src/csharp/Microsoft.Spark/Sql/UDFRegistration.cs
Labels: enhancement

#311 Update worker contract for Spark-3.0.
  src/csharp/Extensions/Microsoft.Spark.Extensions.Delta.E2ETest/DeltaTableTests.cs
  src/csharp/Microsoft.Spark.Worker.UnitTest/CommandExecutorTests.cs
  src/csharp/Microsoft.Spark.Worker.UnitTest/PayloadProcessorTests.cs
  src/csharp/Microsoft.Spark.Worker.UnitTest/PayloadWriter.cs
  src/csharp/Microsoft.Spark.Worker.UnitTest/TaskRunnerTests.cs
  src/csharp/Microsoft.Spark.Worker/Payload.cs
  src/csharp/Microsoft.Spark.Worker/Processor/CommandProcessor.cs
  src/csharp/Microsoft.Spark.Worker/Processor/TaskContextProcessor.cs
  src/csharp/Microsoft.Spark/Sql/Column.cs
  src/csharp/Microsoft.Spark/Versions.cs
Labels: enhancement

#350 Fix E2E FunctionsTests for Spark 3.0.
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/FunctionsTests.cs
  src/csharp/Microsoft.Spark/Attributes.cs
  src/csharp/Microsoft.Spark/Sql/Functions.cs
Labels: enhancement

#353 Fix E2E WindowTests for Spark 3.0.
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/Expressions/WindowTests.cs
  src/csharp/Microsoft.Spark/Sql/Expressions/Window.cs
  src/csharp/Microsoft.Spark/Sql/Functions.cs
Labels: enhancement
