Repository dotnet/spark, pull requests merged in 2020-10, with the labels that each got.

#677 Adding support for DataFrameWriterV2
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/DataFrameWriterV2Tests.cs
  src/csharp/Microsoft.Spark/Sql/DataFrame.cs
  src/csharp/Microsoft.Spark/Sql/DataFrameWriterV2.cs
Labels: enhancement

#665 DataFrameReader.Table
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/DataFrameReaderTests.cs
  src/csharp/Microsoft.Spark/Sql/DataFrameReader.cs
Labels: enhancement

#652 FeatureHasher
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/ML/Feature/BucketizerTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/ML/Feature/CountVectorizerModelTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/ML/Feature/CountVectorizerTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/ML/Feature/FeatureBaseTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/ML/Feature/FeatureHasherTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/ML/Feature/HashingTFTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/ML/Feature/IDFModelTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/ML/Feature/IDFTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/ML/Feature/TokenizerTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/ML/Feature/Word2VecModelTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/ML/Feature/Word2VecTests.cs
  src/csharp/Microsoft.Spark/ML/Feature/FeatureHasher.cs
Labels: enhancement

#699 Fix DaemonWorkerTests.TestsDaemonWorkerTaskRunners and CallbackTests.TestCallbackServer
  src/csharp/Microsoft.Spark.UnitTest/CallbackTests.cs
  src/csharp/Microsoft.Spark.Worker.UnitTest/DaemonWorkerTests.cs
Labels: enhancement

#698 Exposing DataFrame.ToJson()
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/DataFrameTests.cs
  src/csharp/Microsoft.Spark/Sql/DataFrame.cs
Labels: enhancement

#697 Refactor azure-pipelines.yaml
  azure-pipelines-e2e-tests-template.yml
  azure-pipelines.yml
Labels: infrastructure

#705 Remove compatibility tests from the build pipeline.
  azure-pipelines.yml
Labels: infrastructure

#641 Full support for multithreaded applications
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/JvmThreadPoolGCTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/SparkSessionTests.cs
  src/csharp/Microsoft.Spark/Interop/Ipc/JvmBridge.cs
  src/csharp/Microsoft.Spark/Interop/Ipc/JvmThreadPoolGC.cs
  src/csharp/Microsoft.Spark/Interop/Ipc/PayloadHelper.cs
  src/csharp/Microsoft.Spark/Services/ConfigurationService.cs
  src/csharp/Microsoft.Spark/Services/IConfigurationService.cs
  src/csharp/Microsoft.Spark/Sql/SparkSession.cs
  src/scala/microsoft-spark-2.3.x/src/main/scala/org/apache/spark/api/dotnet/DotnetBackendHandler.scala
  src/scala/microsoft-spark-2.3.x/src/main/scala/org/apache/spark/api/dotnet/ThreadPool.scala
  src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/api/dotnet/DotnetBackendHandler.scala
  src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/api/dotnet/ThreadPool.scala
  src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/api/dotnet/DotnetBackendHandler.scala
  src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/api/dotnet/ThreadPool.scala
Labels: enhancement

#717 [Build] Separate publish stage from signing stage.
  azure-pipelines.yml
Labels: infrastructure

#719 Split E2E test build pipeline
  azure-pipelines-e2e-tests-template.yml
  azure-pipelines.yml
  script/download-hadoop-utils.cmd
  script/download-spark-distros.cmd
Labels: infrastructure

#720 Fix issues where extension e2e tests are not being run
  azure-pipelines-e2e-tests-template.yml
Labels: fixing bug

#715 Get Microsoft.Spark and Microsoft.Spark.Worker assembly version information
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/SparkSessionExtensionsTests.cs
  src/csharp/Microsoft.Spark/Experimental/Sql/SparkSessionExtensions.cs
  src/csharp/Microsoft.Spark/Experimental/Utils/AssemblyInfoProvider.cs
Labels: enhancement

#718 Update version check logic on the worker
  src/csharp/Microsoft.Spark.Worker.UnitTest/TestData.cs
  src/csharp/Microsoft.Spark.Worker/TaskRunner.cs
  src/csharp/Microsoft.Spark/Experimental/Sql/SparkSessionExtensions.cs
  src/csharp/Microsoft.Spark/Utils/AssemblyInfoProvider.cs
  src/csharp/Microsoft.Spark/Utils/UdfUtils.cs
  src/csharp/Microsoft.Spark/Versions.cs
Labels: enhancement

#728 Update microsoft-spark JARs to include Scala version
  src/csharp/Microsoft.Spark.E2ETest/SparkFixture.cs
  src/scala/microsoft-spark-2-3/pom.xml
  src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/api/dotnet/CallbackClient.scala
  src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/api/dotnet/CallbackConnection.scala
  src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/api/dotnet/DotnetBackend.scala
  src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/api/dotnet/DotnetBackendHandler.scala
  src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/api/dotnet/DotnetException.scala
  src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/api/dotnet/DotnetRDD.scala
  src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/api/dotnet/JvmBridgeUtils.scala
  src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/api/dotnet/SerDe.scala
  src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/api/dotnet/ThreadPool.scala
  src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
  src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/internal/config/Dotnet.scala
  src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/sql/api/dotnet/SQLUtils.scala
  src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/sql/test/TestUtils.scala
  src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/util/dotnet/Utils.scala
  src/scala/microsoft-spark-2-3/src/test/scala/com/microsoft/scala/AppTest.scala
  src/scala/microsoft-spark-2-4/pom.xml
  src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/api/dotnet/CallbackClient.scala
  src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/api/dotnet/CallbackConnection.scala
  src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/api/dotnet/DotnetBackend.scala
  src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/api/dotnet/DotnetBackendHandler.scala
  src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/api/dotnet/DotnetException.scala
  src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/api/dotnet/DotnetRDD.scala
  src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/api/dotnet/JvmBridgeUtils.scala
  src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/api/dotnet/SerDe.scala
  src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/api/dotnet/ThreadPool.scala
  src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
  src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/internal/config/Dotnet.scala
  src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/sql/api/dotnet/DotnetForeachBatch.scala
  src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/sql/api/dotnet/SQLUtils.scala
  src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/sql/test/TestUtils.scala
  src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/util/dotnet/Utils.scala
  src/scala/microsoft-spark-2-4/src/test/scala/com/microsoft/scala/AppTest.scala
  src/scala/microsoft-spark-3-0/pom.xml
  src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/api/dotnet/CallbackClient.scala
  src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/api/dotnet/CallbackConnection.scala
  src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/api/dotnet/DotnetBackend.scala
  src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/api/dotnet/DotnetBackendHandler.scala
  src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/api/dotnet/DotnetException.scala
  src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/api/dotnet/DotnetRDD.scala
  src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/api/dotnet/JvmBridgeUtils.scala
  src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/api/dotnet/SerDe.scala
  src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/api/dotnet/ThreadPool.scala
  src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
  src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/internal/config/Dotnet.scala
  src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/sql/api/dotnet/DotnetForeachBatch.scala
  src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/sql/api/dotnet/SQLUtils.scala
  src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/sql/test/TestUtils.scala
  src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/util/dotnet/Utils.scala
  src/scala/microsoft-spark-3-0/src/test/scala/com/microsoft/scala/AppTest.scala
  src/scala/pom.xml
Labels: enhancement

#727 Support for DeltaTable.ForName (Delta Lake 0.7+)
  src/csharp/Extensions/Microsoft.Spark.Extensions.Delta.E2ETest/DeltaTableTests.cs
  src/csharp/Extensions/Microsoft.Spark.Extensions.Delta/DeltaLakeVersions.cs
  src/csharp/Extensions/Microsoft.Spark.Extensions.Delta/Tables/DeltaTable.cs
Labels: enhancement

#724 Parallelize all E2E tests in build pipeline
  azure-pipelines-e2e-tests-template.yml
  azure-pipelines.yml
Labels: infrastructure

#735 Shutdown the JVM thread pool to fix the hanging issue while exiting.
  src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/api/dotnet/DotnetBackend.scala
  src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/api/dotnet/ThreadPool.scala
  src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
  src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/api/dotnet/DotnetBackend.scala
  src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/api/dotnet/ThreadPool.scala
  src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
  src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/api/dotnet/DotnetBackend.scala
  src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/api/dotnet/ThreadPool.scala
  src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
Labels: fixing bug

#721 Migration Guide: 0.x to 1.0
  docs/migration-guide.md
Labels: documentation

#736 Isolate all dotnet-interactive statements to use the same jvm thread
  src/csharp/Extensions/Microsoft.Spark.Extensions.DotNet.Interactive/AssemblyKernelExtension.cs
  src/csharp/Microsoft.Spark.Worker/Utils/AssemblyLoaderHelper.cs
  src/csharp/Microsoft.Spark/Interop/Ipc/JvmBridge.cs
  src/csharp/Microsoft.Spark/Services/ConfigurationService.cs
  src/csharp/Microsoft.Spark/Services/IConfigurationService.cs
  src/csharp/Microsoft.Spark/Utils/UdfUtils.cs
Labels: fixing bug

#723 Prep 1.0.0 release
  README.md
  benchmark/scala/pom.xml
  docs/release-notes/1.0.0/release-1.0.0.md
  eng/Versions.props
  src/scala/pom.xml
Labels: documentation

#742 Fix package-worker.ps1 to handle output path with ":"
  script/package-worker.ps1
Labels: infrastructure

#743 migration guide typo
  docs/migration-guide.md
Labels: documentation

#752 Fix signer information mismatch issue
  src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/api/dotnet/DotnetBackend.scala
  src/scala/microsoft-spark-2-3/src/main/scala/org/apache/spark/internal/config/dotnet/Dotnet.scala
  src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/api/dotnet/DotnetBackend.scala
  src/scala/microsoft-spark-2-4/src/main/scala/org/apache/spark/internal/config/dotnet/Dotnet.scala
  src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/api/dotnet/DotnetBackend.scala
  src/scala/microsoft-spark-3-0/src/main/scala/org/apache/spark/internal/config/dotnet/Dotnet.scala
Labels: fixing bug

#745 Fix flaky CallbackTests.TestCallbackHandlers Test
  src/csharp/Microsoft.Spark.UnitTest/CallbackTests.cs
  src/csharp/Microsoft.Spark/Interop/Ipc/CallbackConnection.cs
Labels: fixing bug
