Repository dotnet/spark, pull requests merged in 2020-06, with the labels that each got.

#517 dotnet-interactive assembly extension
  src/csharp/Extensions/Microsoft.Spark.Extensions.DotNet.Interactive.UnitTest/Microsoft.Spark.Extensions.DotNet.Interactive.UnitTest.csproj
  src/csharp/Extensions/Microsoft.Spark.Extensions.DotNet.Interactive.UnitTest/PackageResolverTests.cs
  src/csharp/Extensions/Microsoft.Spark.Extensions.DotNet.Interactive/AssemblyKernelExtension.cs
  src/csharp/Extensions/Microsoft.Spark.Extensions.DotNet.Interactive/Microsoft.Spark.Extensions.DotNet.Interactive.csproj
  src/csharp/Extensions/Microsoft.Spark.Extensions.DotNet.Interactive/PackageResolver.cs
  src/csharp/Extensions/Microsoft.Spark.Extensions.DotNet.Interactive/PackageRestoreContextWrapper.cs
  src/csharp/Extensions/Microsoft.Spark.Extensions.DotNet.Interactive/ResolvedNugetPackage.cs
  src/csharp/Microsoft.Spark.UnitTest/DependencyProviderUtilsTests.cs
  src/csharp/Microsoft.Spark.Worker/Utils/AssemblyLoaderHelper.cs
  src/csharp/Microsoft.Spark.sln
  src/csharp/Microsoft.Spark/Constants.cs
  src/csharp/Microsoft.Spark/Microsoft.Spark.csproj
  src/csharp/Microsoft.Spark/Utils/AssemblyLoader.cs
  src/csharp/Microsoft.Spark/Utils/DependencyProviderUtils.cs
  src/csharp/Microsoft.Spark/Utils/UdfUtils.cs
Labels: enhancement

#524 Add multiple stages for Azure Pipeline
  azure-pipelines.yml
Labels: enhancement

#547 Support Spark 2.4.6
  azure-pipelines.yml
  script/download-spark-distros.cmd
  src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
Labels: enhancement

#558 [fix] Fix broken maven link
  docs/building/ubuntu-instructions.md
Labels: documentation

#560 Fix maven broken link in windows build doc
  docs/building/windows-instructions.md
Labels: documentation

#555 Hyperspace Extension
  src/csharp/Extensions/Microsoft.Spark.Extensions.Hyperspace.E2ETest/Constants.cs
  src/csharp/Extensions/Microsoft.Spark.Extensions.Hyperspace.E2ETest/HyperspaceFixture.cs
  src/csharp/Extensions/Microsoft.Spark.Extensions.Hyperspace.E2ETest/HyperspaceTests.cs
  src/csharp/Extensions/Microsoft.Spark.Extensions.Hyperspace.E2ETest/Index/IndexConfigTests.cs
  src/csharp/Extensions/Microsoft.Spark.Extensions.Hyperspace.E2ETest/Microsoft.Spark.Extensions.Hyperspace.E2ETest.csproj
  src/csharp/Extensions/Microsoft.Spark.Extensions.Hyperspace/Hyperspace.cs
  src/csharp/Extensions/Microsoft.Spark.Extensions.Hyperspace/HyperspaceSparkSessionExtensions.cs
  src/csharp/Extensions/Microsoft.Spark.Extensions.Hyperspace/Index/Builder.cs
  src/csharp/Extensions/Microsoft.Spark.Extensions.Hyperspace/Index/IndexConfig.cs
  src/csharp/Extensions/Microsoft.Spark.Extensions.Hyperspace/Microsoft.Spark.Extensions.Hyperspace.csproj
  src/csharp/Microsoft.Spark.E2ETest/Microsoft.Spark.E2ETest.csproj
  src/csharp/Microsoft.Spark.sln
  src/csharp/Microsoft.Spark/Interop/Internal/Scala/Seq.cs
  src/csharp/Microsoft.Spark/Microsoft.Spark.csproj
Labels: enhancement

#551 UDF bug fix caused by ThreadStatic BroadcastVariablesRegistry
  src/csharp/Microsoft.Spark.E2ETest/UdfTests/UdfSimpleTypesTests.cs
  src/csharp/Microsoft.Spark/Broadcast.cs
Labels: bug

#530 Fix NRE for TimestampType and DateType and support nullable value types
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/SparkSessionTests.cs
  src/csharp/Microsoft.Spark/Sql/SparkSession.cs
  src/csharp/Microsoft.Spark/Sql/Types/SimpleTypes.cs
Labels: enhancement

#565 Bugfix for Microsoft.Spark.Extensions.DotNet.Interactive duplicate file exception
  src/csharp/Extensions/Microsoft.Spark.Extensions.DotNet.Interactive/AssemblyKernelExtension.cs
Labels: bug

#570 [Bug] AssemblyLoader should use absolute assembly path when loading assemblies
  src/csharp/Microsoft.Spark.UnitTest/AssemblyLoaderTests.cs
  src/csharp/Microsoft.Spark/Utils/AssemblyLoader.cs
Labels: bug

#572 Prep 0.12.1 Release
  README.md
  benchmark/scala/pom.xml
  docs/release-notes/0.12.1/release-0.12.1.md
  eng/Versions.props
  src/scala/pom.xml
Labels: enhancement
