Repository dotnet/spark, pull requests merged in 2020-09, with the labels that each got.

#646 Switch on C# pattern matching for matching types
  src/csharp/Microsoft.Spark/Sql/ArrowArrayHelpers.cs
Labels: enhancement

#655 TestSignaturesV2_3_X Tests for Spark-3.0.0
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/DataFrameTests.cs
  src/csharp/Microsoft.Spark/Sql/DataFrame.cs
  src/csharp/Microsoft.Spark/Sql/RowCollector.cs
Labels: enhancement

#656 Update azure-pipeline.yml to include comments on why E2E forward compatibility test does not run against Spark 2.4.6.
  azure-pipelines.yml
Labels: infrastructure

#348 Set up build pipeline for Spark-3.0.0
  azure-pipelines.yml
  script/download-spark-distros.cmd
  src/csharp/Extensions/Microsoft.Spark.Extensions.Delta.E2ETest/DeltaFixture.cs
  src/csharp/Extensions/Microsoft.Spark.Extensions.Delta.E2ETest/DeltaTableTests.cs
  src/csharp/Extensions/Microsoft.Spark.Extensions.Hyperspace.E2ETest/HyperspaceFixture.cs
  src/csharp/Extensions/Microsoft.Spark.Extensions.Hyperspace.E2ETest/HyperspaceTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/BroadcastTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/DataFrameTests.cs
  src/csharp/Microsoft.Spark.E2ETest/SparkSettings.cs
  src/csharp/Microsoft.Spark.E2ETest/Utils/VersionBasedFacts.cs
  src/scala/microsoft-spark-3.0.x/pom.xml
  src/scala/pom.xml
Labels: enhancement, infrastructure

#661 Return UTF-8 encoded string from JVM => CLR
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/SerDeTests.cs
  src/scala/microsoft-spark-2.3.x/src/main/scala/org/apache/spark/api/dotnet/SerDe.scala
  src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/api/dotnet/SerDe.scala
  src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/api/dotnet/SerDe.scala
Labels: enhancement

#649 Spark 3.0 readiness part 2
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/FunctionsTests.cs
  src/csharp/Microsoft.Spark/Sql/Functions.cs
Labels: enhancement

#667 Support Spark 2.4.7 & 3.0.1
  azure-pipelines.yml
  script/download-spark-distros.cmd
  src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
  src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
Labels: enhancement

#647 Spark 3.0 readiness part 1
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/DataFrameFunctionsTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/DataFrameTests.cs
  src/csharp/Microsoft.Spark/Sql/DataFrame.cs
  src/csharp/Microsoft.Spark/Sql/DataFrameStatFunctions.cs
  src/csharp/Microsoft.Spark/Sql/SparkSession.cs
Labels: enhancement

#644 Add simpleworker test
  src/csharp/Microsoft.Spark.Worker.UnitTest/SimpleWorkerTests.cs
  src/csharp/Microsoft.Spark.Worker.UnitTest/TaskRunnerTests.cs
  src/csharp/Microsoft.Spark.Worker/SimpleWorker.cs
Labels: enhancement

#688 Expose DataFrame.Transform
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/DataFrameTests.cs
  src/csharp/Microsoft.Spark/Sql/DataFrame.cs
Labels: enhancement

#690 Expose StreamingQueryManager
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/SparkSessionTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/Streaming/StreamingQueryManagerTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/Streaming/StreamingQueryTests.cs
  src/csharp/Microsoft.Spark.E2ETest/Utils/MemoryStream.cs
  src/csharp/Microsoft.Spark/Sql/SparkSession.cs
  src/csharp/Microsoft.Spark/Sql/Streaming/StreamingQuery.cs
  src/csharp/Microsoft.Spark/Sql/Streaming/StreamingQueryException.cs
  src/csharp/Microsoft.Spark/Sql/Streaming/StreamingQueryManager.cs
  src/scala/microsoft-spark-2.3.x/src/main/scala/org/apache/spark/sql/test/TestUtils.scala
  src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/sql/test/TestUtils.scala
  src/scala/microsoft-spark-3.0.x/src/main/scala/org/apache/spark/sql/test/TestUtils.scala
Labels: enhancement

#689 PicklingUdfWrapper cache type information
  src/csharp/Microsoft.Spark/Sql/PicklingUdfWrapper.cs
  src/csharp/Microsoft.Spark/Utils/TypeConverter.cs
  src/csharp/Microsoft.Spark/Utils/UdfSerDe.cs
Labels: enhancement

#489 Broadcast encryption support
  azure-pipelines.yml
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/BroadcastTests.cs
  src/csharp/Microsoft.Spark.Worker/Processor/BroadcastVariableProcessor.cs
  src/csharp/Microsoft.Spark/Broadcast.cs
Labels: enhancement

#692 Enable more E2E tests for Delta running under Spark 3.0.
  src/csharp/Extensions/Microsoft.Spark.Extensions.Delta.E2ETest/DeltaFixture.cs
  src/csharp/Extensions/Microsoft.Spark.Extensions.Delta.E2ETest/DeltaTableTests.cs
Labels: enhancement

#691 Move Microsoft.Spark.Experimental to Microsoft.Spark
  benchmark/csharp/Microsoft.Spark.Benchmark.sln
  benchmark/csharp/Tpch/Tpch.csproj
  benchmark/csharp/Tpch/TpchFunctionalQueries.cs
  examples/Microsoft.Spark.CSharp.Examples/Microsoft.Spark.CSharp.Examples.csproj
  examples/Microsoft.Spark.CSharp.Examples/Sql/Batch/VectorDataFrameUdfs.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/DataFrameTests.cs
  src/csharp/Microsoft.Spark.E2ETest/Microsoft.Spark.E2ETest.csproj
  src/csharp/Microsoft.Spark.Experimental/Microsoft.Spark.Experimental.csproj
  src/csharp/Microsoft.Spark.Experimental/Sql/RelationalGroupedDatasetExtensions.cs
  src/csharp/Microsoft.Spark.sln
  src/csharp/Microsoft.Spark/Microsoft.Spark.csproj
  src/csharp/Microsoft.Spark/Sql/ArrowFunctions.cs
  src/csharp/Microsoft.Spark/Sql/DataFrameFunctions.cs
  src/csharp/Microsoft.Spark/Sql/DataFrameUdfRegistrationExtensions.cs
  src/csharp/Microsoft.Spark/Sql/Functions.cs
  src/csharp/Microsoft.Spark/Sql/RelationalGroupedDataset.cs
  src/csharp/Microsoft.Spark/Sql/UdfRegistrationExtensions.cs
Labels: enhancement
