Repository dotnet/spark, pull requests merged in 2021-04, with the labels that each got.

#886 Spark 3.1.0 APIs - DataStreamReader and DataStreamWriter
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/Streaming/DataStreamReaderTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/Streaming/DataStreamWriterTests.cs
  src/csharp/Microsoft.Spark.E2ETest/Utils/SQLUtils.cs
  src/csharp/Microsoft.Spark/Sql/Streaming/DataStreamReader.cs
  src/csharp/Microsoft.Spark/Sql/Streaming/DataStreamWriter.cs
  src/csharp/Microsoft.Spark/Versions.cs
Labels: enhancement

#887 Spark 3.1.0 APIs - Column
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/ColumnTests.cs
  src/csharp/Microsoft.Spark/Sql/Column.cs
Labels: enhancement

#891 Revert "Temporarily disable support for Spark 3.1.1 to release .NET for Apache Spark 1.1"
  azure-pipelines.yml
  src/scala/pom.xml
Labels: enhancement

#888 Spark 3.1.0 APIs - DataFrame
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/DataFrameTests.cs
  src/csharp/Microsoft.Spark/Sql/DataFrame.cs
Labels: enhancement

#890 Spark 3.1.0 APIs - Functions
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/FunctionsTests.cs
  src/csharp/Microsoft.Spark/Sql/Functions.cs
Labels: enhancement

#893 Spark 3.1.0 APIs - Catalog
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/CatalogTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/FunctionsTests.cs
  src/csharp/Microsoft.Spark/Sql/Catalog/Catalog.cs
Labels: enhancement

#896 Disable forward/backward tests in preparation for v2.0.0
  azure-pipelines-e2e-tests-template.yml
  azure-pipelines.yml
Labels: infrastructure

#889 Spark 3.1.0 APIs - SparkContext
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/SparkContextTests.cs
  src/csharp/Microsoft.Spark.E2ETest/Resources/archive.zip
  src/csharp/Microsoft.Spark/SparkContext.cs
Labels: enhancement

#907 StreamingQueryManagerTests test fix
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/Streaming/DataStreamWriterTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/Streaming/StreamingQueryManagerTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/Streaming/StreamingQueryTests.cs
Labels: fixing bug
