Repository dotnet/spark, pull requests merged in 2021-03, with the labels that each got.

#834 Add microsoft-spark-3-1 jar
  src/scala/microsoft-spark-3-1/pom.xml
  src/scala/microsoft-spark-3-1/src/main/scala/org/apache/spark/api/dotnet/CallbackClient.scala
  src/scala/microsoft-spark-3-1/src/main/scala/org/apache/spark/api/dotnet/CallbackConnection.scala
  src/scala/microsoft-spark-3-1/src/main/scala/org/apache/spark/api/dotnet/DotnetBackend.scala
  src/scala/microsoft-spark-3-1/src/main/scala/org/apache/spark/api/dotnet/DotnetBackendHandler.scala
  src/scala/microsoft-spark-3-1/src/main/scala/org/apache/spark/api/dotnet/DotnetException.scala
  src/scala/microsoft-spark-3-1/src/main/scala/org/apache/spark/api/dotnet/DotnetRDD.scala
  src/scala/microsoft-spark-3-1/src/main/scala/org/apache/spark/api/dotnet/JVMObjectTracker.scala
  src/scala/microsoft-spark-3-1/src/main/scala/org/apache/spark/api/dotnet/JvmBridgeUtils.scala
  src/scala/microsoft-spark-3-1/src/main/scala/org/apache/spark/api/dotnet/SerDe.scala
  src/scala/microsoft-spark-3-1/src/main/scala/org/apache/spark/api/dotnet/ThreadPool.scala
  src/scala/microsoft-spark-3-1/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala
  src/scala/microsoft-spark-3-1/src/main/scala/org/apache/spark/internal/config/dotnet/Dotnet.scala
  src/scala/microsoft-spark-3-1/src/main/scala/org/apache/spark/sql/api/dotnet/DotnetForeachBatch.scala
  src/scala/microsoft-spark-3-1/src/main/scala/org/apache/spark/sql/api/dotnet/SQLUtils.scala
  src/scala/microsoft-spark-3-1/src/main/scala/org/apache/spark/sql/test/TestUtils.scala
  src/scala/microsoft-spark-3-1/src/main/scala/org/apache/spark/util/dotnet/Utils.scala
  src/scala/microsoft-spark-3-1/src/test/scala/org/apache/spark/api/dotnet/DotnetBackendHandlerTest.scala
  src/scala/microsoft-spark-3-1/src/test/scala/org/apache/spark/api/dotnet/DotnetBackendTest.scala
  src/scala/microsoft-spark-3-1/src/test/scala/org/apache/spark/api/dotnet/Extensions.scala
  src/scala/microsoft-spark-3-1/src/test/scala/org/apache/spark/api/dotnet/JVMObjectTrackerTest.scala
  src/scala/microsoft-spark-3-1/src/test/scala/org/apache/spark/api/dotnet/SerDeTest.scala
Labels: enhancement

#849 Update azure-pipelines.yml to remove master.
  azure-pipelines.yml
Labels: infrastructure

#868 Bug Fix for Spark 3.x - Avoid converting converted Row values
  azure-pipelines.yml
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/RowTests.cs
  src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/Streaming/DataStreamWriterTests.cs
  src/csharp/Microsoft.Spark.E2ETest/UdfTests/UdfSimpleTypesTests.cs
  src/csharp/Microsoft.Spark.UnitTest/Sql/RowTests.cs
  src/csharp/Microsoft.Spark.Worker/Command/SqlCommandExecutor.cs
  src/csharp/Microsoft.Spark/RDD/Collector.cs
  src/csharp/Microsoft.Spark/Sql/RowCollector.cs
  src/csharp/Microsoft.Spark/Sql/RowConstructor.cs
  src/csharp/Microsoft.Spark/Sql/Types/ComplexTypes.cs
  src/csharp/Microsoft.Spark/Sql/Types/DataType.cs
Labels: fixing bug

#871 Add 'Z' to the string format in Timestamp.ToString() to indicate UTC time.
  azure-pipelines.yml
  src/csharp/Microsoft.Spark.E2ETest/UdfTests/UdfSimpleTypesTests.cs
  src/csharp/Microsoft.Spark.UnitTest/Sql/TimestampTests.cs
  src/csharp/Microsoft.Spark/Sql/Types/Timestamp.cs
Labels: fixing bug

#870 Temporarily disable support for Spark 3.1.1 to release .NET for Apache Spark 1.1
  azure-pipelines.yml
  src/scala/pom.xml
Labels: enhancement
